//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GWdbEntities : DbContext
    {
        public GWdbEntities()
            : base("name=GWdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCCAccomodation> tblCCAccomodations { get; set; }
        public DbSet<tblCCArrangement> tblCCArrangements { get; set; }
        public DbSet<tblCCCompany> tblCCCompanies { get; set; }
        public DbSet<tblCCDepartment> tblCCDepartments { get; set; }
        public DbSet<tblCCFlight> tblCCFlights { get; set; }
        public DbSet<tblCCNationality> tblCCNationalities { get; set; }
        public DbSet<tblCCPersonnel> tblCCPersonnels { get; set; }
        public DbSet<tblCCPickup> tblCCPickups { get; set; }
        public DbSet<tblCCShipName> tblCCShipNames { get; set; }
        public DbSet<tblCCUser> tblCCUsers { get; set; }
        public DbSet<tblCCUserCompanyAccess> tblCCUserCompanyAccesses { get; set; }
        public DbSet<tlkpCountryAirport> tlkpCountryAirports { get; set; }
        public DbSet<tlkpType> tlkpTypes { get; set; }
    }
}
