//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCCompany
    {
        public tblCCCompany()
        {
            this.tblCCDepartments = new HashSet<tblCCDepartment>();
            this.tblCCUserCompanyAccesses = new HashSet<tblCCUserCompanyAccess>();
        }
    
        public string cccoCompanyID { get; set; }
        public string cccoName { get; set; }
        public string cccoImage { get; set; }
        public Nullable<short> cccoGMT { get; set; }
    
        public virtual ICollection<tblCCDepartment> tblCCDepartments { get; set; }
        public virtual ICollection<tblCCUserCompanyAccess> tblCCUserCompanyAccesses { get; set; }
    }
}
