//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCShipName
    {
        public tblCCShipName()
        {
            this.tblCCArrangements = new HashSet<tblCCArrangement>();
        }
    
        public System.Guid ccsnShipNameID { get; set; }
        public Nullable<System.Guid> ccsnIDShip { get; set; }
        public Nullable<System.Guid> ccsnShipID { get; set; }
        public string ccsnName { get; set; }
        public Nullable<int> ccsnIMO { get; set; }
        public bool ccsnIsActive { get; set; }
        public string ccsnSiteID { get; set; }
        public byte[] ccsnTimeID { get; set; }
        public System.Guid ccsnRowGUID { get; set; }
    
        public virtual ICollection<tblCCArrangement> tblCCArrangements { get; set; }
    }
}
