//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCArrangement
    {
        public tblCCArrangement()
        {
            this.tblCCPersonnels = new HashSet<tblCCPersonnel>();
        }
    
        public System.Guid ccarArrangeID { get; set; }
        public System.Guid ccarShipNameID { get; set; }
        public System.DateTime ccarETADate { get; set; }
        public Nullable<System.DateTime> ccarETATime { get; set; }
        public Nullable<System.DateTime> ccarETDDate { get; set; }
        public Nullable<System.DateTime> ccarETDTime { get; set; }
        public string ccarCountryFrom { get; set; }
        public string ccarPortFrom { get; set; }
        public string ccarPortNameFrom { get; set; }
        public string ccarCountryTo { get; set; }
        public string ccarPortTo { get; set; }
        public string ccarPortNameTo { get; set; }
        public string ccarCountryIn { get; set; }
        public string ccarPortIn { get; set; }
        public string ccarPortNameIn { get; set; }
        public string ccarTerminal { get; set; }
        public string ccarFlag { get; set; }
        public string ccarPrincipalName { get; set; }
        public string ccarShipTypeID { get; set; }
        public string ccarVoyageNo { get; set; }
        public Nullable<System.Guid> ccarReportToShipMasterGenBy { get; set; }
        public Nullable<System.DateTime> ccarReportToShipMasterGenDt { get; set; }
        public bool ccarIsOpen { get; set; }
        public bool ccarIsCancelled { get; set; }
        public bool ccarIsActive { get; set; }
        public Nullable<int> ccarK2ETAPID { get; set; }
        public Nullable<int> ccarK2ETDPID { get; set; }
        public string ccarCompanyID { get; set; }
        public System.Guid ccarPIC { get; set; }
        public System.Guid ccarCreatedBy { get; set; }
        public System.DateTime ccarCreatedDt { get; set; }
        public System.Guid ccarUpdatedBy { get; set; }
        public System.DateTime ccarUpdatedDt { get; set; }
        public string ccarSiteID { get; set; }
        public byte[] ccarTimeID { get; set; }
        public System.Guid ccarRowGUID { get; set; }
    
        public virtual tblCCShipName tblCCShipName { get; set; }
        public virtual ICollection<tblCCPersonnel> tblCCPersonnels { get; set; }
    }
}
