//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCFlight
    {
        public System.Guid ccflArrangeID { get; set; }
        public System.Guid ccflPersonnelID { get; set; }
        public System.Guid ccflFlightID { get; set; }
        public string ccflCarrier { get; set; }
        public string ccflFlight { get; set; }
        public string ccflOrigin { get; set; }
        public string ccflDestination { get; set; }
        public Nullable<System.DateTime> ccflDepartDate { get; set; }
        public Nullable<System.DateTime> ccflDepartTime { get; set; }
        public Nullable<System.DateTime> ccflArrivalDate { get; set; }
        public Nullable<System.DateTime> ccflArrivalTime { get; set; }
        public Nullable<int> ccflK2ETAPID { get; set; }
        public bool ccflIsActive { get; set; }
        public string ccflSiteID { get; set; }
        public byte[] ccflTimeID { get; set; }
        public System.Guid ccflRowGUID { get; set; }
    
        public virtual tblCCPersonnel tblCCPersonnel { get; set; }
    }
}
