//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCAccomodation
    {
        public System.Guid ccacArrangeID { get; set; }
        public System.Guid ccacPersonnelID { get; set; }
        public System.Guid ccacAccommodationID { get; set; }
        public string ccacRoomTypeID { get; set; }
        public System.DateTime ccacCheckInDate { get; set; }
        public System.DateTime ccacCheckOutDate { get; set; }
        public string ccacSupplierNo { get; set; }
        public Nullable<System.Guid> ccacSharePersonnelID { get; set; }
        public Nullable<System.DateTime> ccacBookDate { get; set; }
        public bool ccacIsNoShow { get; set; }
        public bool ccacIsCancelled { get; set; }
        public bool ccacIsActive { get; set; }
        public string ccacRemarks { get; set; }
        public string ccacSiteID { get; set; }
        public byte[] ccacTimeID { get; set; }
        public Nullable<System.Guid> ccacRowGUID { get; set; }
    
        public virtual tblCCPersonnel tblCCPersonnel { get; set; }
    }
}
