//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCUser
    {
        public System.Guid ccusUserID { get; set; }
        public string ccusDisplayName { get; set; }
        public string ccusContactNo { get; set; }
        public string ccusEmail { get; set; }
        public string ccusDepartmentID { get; set; }
        public string ccusCompanyID { get; set; }
    }
}
