//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCPickup
    {
        public System.Guid ccpkArrangeID { get; set; }
        public System.Guid ccpkPersonnelID { get; set; }
        public System.Guid ccpkPickupID { get; set; }
        public System.DateTime ccpkPickupDate { get; set; }
        public System.DateTime ccpkPickupTime { get; set; }
        public string ccpkOrigin { get; set; }
        public string ccpkDestination { get; set; }
        public string ccpkSupplierNo { get; set; }
        public bool ccpkIsPrivateTransfer { get; set; }
        public bool ccpkIsNoShow { get; set; }
        public bool ccpkIsCancelled { get; set; }
        public bool ccpkIsActive { get; set; }
        public string ccpkRemarks { get; set; }
        public string ccpkSiteID { get; set; }
        public byte[] ccpkTimeID { get; set; }
        public System.Guid ccpkRowGUID { get; set; }
    
        public virtual tblCCPersonnel tblCCPersonnel { get; set; }
    }
}
