//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCDepartment
    {
        public string ccdeCompanyID { get; set; }
        public string ccdeDepartmentID { get; set; }
        public string ccdeName { get; set; }
        public string ccdeEmail { get; set; }
    
        public virtual tblCCCompany tblCCCompany { get; set; }
    }
}
