//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCCPersonnel
    {
        public tblCCPersonnel()
        {
            this.tblCCAccomodations = new HashSet<tblCCAccomodation>();
            this.tblCCFlights = new HashSet<tblCCFlight>();
            this.tblCCPickups = new HashSet<tblCCPickup>();
        }
    
        public System.Guid ccpeArrangeID { get; set; }
        public System.Guid ccpePersonnelID { get; set; }
        public string ccpeFirstName { get; set; }
        public string ccpeLastName { get; set; }
        public string ccpePosition { get; set; }
        public string ccpeCategoryID { get; set; }
        public string ccpeCountryID { get; set; }
        public string ccpeSignerID { get; set; }
        public string ccpeGender { get; set; }
        public string ccpeClientRefNo { get; set; }
        public bool ccpeIsOkToBoard { get; set; }
        public Nullable<System.Guid> ccpeOkToBoardGenBy { get; set; }
        public Nullable<System.DateTime> ccpeOkToBoardGenDt { get; set; }
        public Nullable<System.Guid> ccpeReportForAccomGenBy { get; set; }
        public Nullable<System.DateTime> ccpeReportForAccomGenDt { get; set; }
        public Nullable<System.Guid> ccpeReportForTransGenBy { get; set; }
        public Nullable<System.DateTime> ccpeReportForTransGenDt { get; set; }
        public bool ccpeIsCancelled { get; set; }
        public bool ccpeIsActive { get; set; }
        public string ccpeRemarks { get; set; }
        public string ccpeSiteID { get; set; }
        public byte[] ccpeTimeID { get; set; }
        public System.Guid ccpeRowGUID { get; set; }
    
        public virtual ICollection<tblCCAccomodation> tblCCAccomodations { get; set; }
        public virtual tblCCArrangement tblCCArrangement { get; set; }
        public virtual ICollection<tblCCFlight> tblCCFlights { get; set; }
        public virtual ICollection<tblCCPickup> tblCCPickups { get; set; }
    }
}
