//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkpCountryAirport
    {
        public string cairCountryID { get; set; }
        public string cairAirportID { get; set; }
        public string cairName { get; set; }
        public string cairCountryCode { get; set; }
    }
}
