//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkToBoardServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlkpType
    {
        public string typeSystemID { get; set; }
        public string typeTypeID { get; set; }
        public string typeDescription { get; set; }
    }
}
