// <auto-generated />
namespace DatabaseSynchronizer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddETDToArrangement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddETDToArrangement));
        
        string IMigrationMetadata.Id
        {
            get { return "201507150313492_AddETDToArrangement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
