// <auto-generated />
namespace DatabaseSynchronizer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTableReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTableReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201507011250510_AddTableReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
